version: 0.2

env:
  variables:
    DATABASE_HOST: "not-used"
    DATABASE_USER: "not-used"
    DATABASE_PASSWORD: "not-used"
    DATABASE_DB_NAME: "not-used"

phases:
  install:
    commands:
      - echo Install started on 'date'
      - yum -y install python3.7
      - pip-3.7 install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - python -m py_compile *.py
  post_build:
    commands:
      - echo Build completed on 'date'

artifacts:
  files:
    - 'cover/*'