version: 0.2

env:
  variables:
    DATABASE_HOST: "not-used"
    DATABASE_USER: "not-used"
    DATABASE_PASSWORD: "not-used"
    DATABASE_DB_NAME: "not-used"

phases:
  install:
    commands:
      - echo Install started on 'date'
      - yum -y install python3.7
      - pip-3.7 install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - python -m py_compile *.py
      - echo building and tagging image
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 687995572327.dkr.ecr.us-west-2.amazonaws.com
      - docker build -t python-app .
      - docker tag python-app:latest 687995572327.dkr.ecr.us-west-2.amazonaws.com/python-app:latest
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo pushing to ECR
      - docker push 687995572327.dkr.ecr.us-west-2.amazonaws.com/python-app:latest
